server:
  port: 8081

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/juansoto90/microserviceprueba.git
          searchPaths: config-data